---
- name: restart promtail
  systemd:
    daemon_reload: true
    name: promtail
    state: restarted
  become: true
  tags: promtail

- name: reload promtail
  systemd:
    name: promtail
    state: reloaded
  become: true
  tags: promtail

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: promtail
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: promtail
  become: true